name: CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npm run eslint
            - name: Test and Coverage
              run: npm run test
              env:
                  DB_HOST: db.ilggocztfygakyoidvux.supabase.co
                  DB_PORT: 5432
                  DB_USERNAME: postgres
                  DB_PASSWORD: PumpX8ZIkYQzRuz2
                  DB_NAME: postgres
            - name: Build-ts
              run: npm run build
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
